"""rebuild db

Revision ID: 867ca82914ec
Revises: f25bb486ed52
Create Date: 2023-02-23 03:24:34.944839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867ca82914ec'
down_revision = 'f25bb486ed52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
